### ISSUE TITLE
Having direct access to your own markdowns and publishing from it >  github's database.

### ISSUE THREAD

**Issue by sai-prasanna** [scarecrow1123/blog#4]
Try https://github.com/mmistakes/minimal-mistakes

**Comment by scarecrow1123** [comment]
I'm done with Jekyll themes. And this current setup is too convenient for me personally.

**Comment by sai-prasanna** [comment]
But this won't get indexed or isn't linkable la ..

**Comment by scarecrow1123** [comment]
Hmm.. Not really. I would prefer discussing this over other published threads rather than in a new issue thread. This is because I'm planning to only have the posts in Issues tab and nothing else. So I may be deleting this particular thread soon. Sorry about that.
